/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 16 06:21:15 GMT 2019
 */

package org.apache.commons.collections4.set;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.NavigableSet;
import java.util.TreeSet;
import org.apache.commons.collections4.set.UnmodifiableNavigableSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class AbstractNavigableSetDecorator_ESTest extends AbstractNavigableSetDecorator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TreeSet<Object> treeSet0 = new TreeSet<Object>();
      NavigableSet<Object> navigableSet0 = UnmodifiableNavigableSet.unmodifiableNavigableSet((NavigableSet<Object>) treeSet0);
      boolean boolean0 = treeSet0.addAll(navigableSet0);
      assertFalse(boolean0);
  }
}
