/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 16 06:20:24 GMT 2019
 */

package org.apache.commons.collections4.bag;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Collection;
import org.apache.commons.collections4.bag.HashBag;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HashBag_ESTest extends HashBag_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HashBag<Integer> hashBag0 = new HashBag<Integer>();
      HashBag<Object> hashBag1 = new HashBag<Object>(hashBag0);
      assertEquals(0, hashBag1.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HashBag<Integer> hashBag0 = null;
      try {
        hashBag0 = new HashBag<Integer>((Collection<? extends Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.collections4.bag.AbstractMapBag", e);
      }
  }
}
