/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 16 06:21:34 GMT 2019
 */

package org.apache.commons.collections4.sequence;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.collections4.sequence.CommandVisitor;
import org.apache.commons.collections4.sequence.InsertCommand;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class InsertCommand_ESTest extends InsertCommand_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      InsertCommand<String> insertCommand0 = new InsertCommand<String>("");
      // Undeclared exception!
      try { 
        insertCommand0.accept((CommandVisitor<String>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.collections4.sequence.InsertCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer integer0 = new Integer(0);
      InsertCommand<Integer> insertCommand0 = new InsertCommand<Integer>(integer0);
      CommandVisitor<Integer> commandVisitor0 = (CommandVisitor<Integer>) mock(CommandVisitor.class, new ViolatedAssumptionAnswer());
      insertCommand0.accept(commandVisitor0);
  }
}
